### PR TITLE
feat: add ListExternalContact,GetExternalContact,RemarkExternalContact

### PR DESCRIPTION
**Pull request by w3xse7en**
Support manage externalcontact apis
ListExternalContact See doc: https://work.weixin.qq.com/api/doc/90000/90135/92113
GetExternalContact See doc: https://work.weixin.qq.com/api/doc/90000/90135/92114
RemarkExternalContact  See doc: https://work.weixin.qq.com/api/doc/90000/90135/92115

better for goland coders
.gitignore add intellij+all

### CODE REVIEW

**Comment by w3xse7en** [comment]
review please @xen0n

**Comment by xen0n** [comment]
Sorry for not noticing this! Probably this PR's notification got accidentally removed by me. I'm reviewing this very soon. (From a cursory look it seems great!)

**Review by xen0n — COMMENTED** [review]
Things look good, especially coding-style-wise (big *thanks* for following my undocumented and somewhat paranoid half-Go-half-Rust style throughout!)

One thing I noticed is the naming of some types and methods, some of them are clearly Chinglish. Would you mind me changing some of them after merging this PR?

**Comment by w3xse7en** [comment]
forgive my poor english and I don't mind

**Review by xen0n — APPROVED** [review]

**Comment by xen0n** [comment]
Fine then, I'll take this PR and revise things afterwards hopefully soon. Thanks for your contribution!

**Pull request merged**
