### PR TITLE
feat: add jsApiTicket, jsApiTicketAgentConfig and refactor(token): accessToken

### PR DESCRIPTION
**Pull request by w3xse7en**
Support  jsApiTicket, jsApiTicketAgentConfig

doc: https://open.work.weixin.qq.com/api/doc/90000/90136/90506

jsApiTicket, jsApiTicketAgentConfig similar with accessToken, they all needs cache in system

so i reference the accesstoken design, refact token to support accessToken, jsApiTicket and jsApiTicketAgentConfig

### CODE REVIEW

**Review by xen0n — COMMENTED** [review]
Thanks for your continued contribution and refactoring work!

Regarding the API design, according to the official docs you linked to, the JSAPI ticket and signing logic indeed must be done server-side for security reasons, and I presume this is the reason of the PR.

However, the feature is not useful for those downstream users without a corresponding web app, so I suggest hiding all JSAPI-specific logic inside some helper struct.

Aside from this, the extraction of token logic could go deeper. Store a reference to the parent `*WorkwxApp` object inside `type token`, then you can get rid of all polymorphic `switch`es and `tokenType` marker too. In other words, ideally only `workwxApp.getToken()` and something like `workwxApp.NewJSAPITicketContext()` and `jsapiCtx.GetTicket()` should remain, and everything is nicely statically dispatched.

**Comment by w3xse7en** [comment]
`switch` and `tokenType`  is removed in new commit 

---

> something like `workwxApp.NewJSAPITicketContext()` and `jsapiCtx.GetTicket()`

about this there is some question

```
        workwxApp := workwx.New(corpID).WithApp(corpSecret, agentId)

	// this is old design like accessToken, keep the token alive
	workwxApp.SpawnJsApiTicketRefresher()
       
	workwxApp.GetJsApiTicket()

        // is SpawnJsApiTicketRefresher inside NewJSAPITicketContext?
        // when and where flash new ticket?
	jsapiCtx:=workwxApp.NewJSAPITicketContext()
	ticket:=jsapiCtx.GetTicket()

```

**Comment by xen0n** [comment]
> // is SpawnJsApiTicketRefresher inside NewJSAPITicketContext?
> // when and where flash new ticket?

Symmetry is desired; i.e. the way to keep JSAPI ticket up-to-date should be identical to that for the main token, except for the types and exact method to use.

```go
// The way you instantiate WorkwxApp and refresh your access token
cl := workwx.New(...)
app := cl.WithApp(...)
app.SpawnAccessTokenRefresherWithContext(ctx)

// The way you instantiate JSAPITicketContext and refresh your JSAPI ticket
ticketCtx := cl.NewJSAPITicketContext()
ticketCtx.SpawnTicketRefresherWithContext(ctx)
```

I have read the docs in more detail, JSAPI tickets are exchanged with access tokens, so the ticket context must keep a reference to the outermost client object. Luckily we're in the same package so things like `cl.getAccessToken()` can still be kept private.

**Comment by w3xse7en** [comment]
impossible to get `cl.getAccessToken()`, but `app.getAccessToken()` is ok

so there are three ways to get the ticket token

```go
cl := workwx.New(...)
app := cl.WithApp(...)
app.SpawnAccessTokenRefresherWithContext(ctx)

// one 
ticketCtx := app.NewJSAPITicketContext()
ticketCtx.SpawnTicketRefresherWithContext(ctx)
token,err :=ticketCtx.GetToken()

// two
app.NewJSAPITicketContext().SpawnTicketRefresherWithContext(ctx)
ticket,err :=app.GetJsApiTicket()

// three
// i recommend this case similar with accessToken
app.SpawnJsApiTicketRefresherWithContext(ctx)
ticket,err :=app.GetJsApiTicket()

```

**Comment by xen0n** [comment]
> impossible to get `cl.getAccessToken()`, but `app.getAccessToken()` is ok
> 
> so there are three ways to get the ticket token
> 
> ```go
> cl := workwx.New(...)
> app := cl.WithApp(...)
> app.SpawnAccessTokenRefresherWithContext(ctx)
> 
> // three
> // i recommend this case similar with accessToken
> app.SpawnJsApiTicketRefresherWithContext(ctx)
> ticket,err :=app.GetJsApiTicket()
> ```

I like the 3rd user-interface best, better than I earlier thought! JSAPI tickets are not meant for use by backend code, and is conceptually near-identical to an "access token", so plz go ahead with this!

**Comment by xen0n** [comment]
A few words on the casing:

`JsApi` seems more Rustic than Gonic (Go prefers upper-casing the whole acronym; thinks `std::net::TcpStream` vs `(net).TCPConn`, etc.) Also, well-known acronyms including `Api` will get linted. So I think `JSAPI` should be the right spelling.

**Review by xen0n — APPROVED** [review]
Seems good, I'll merge it.

Thanks for the addition!

**Pull request merged**
