### PR TITLE
Fix typo in DeptInfo json decorator

### PR DESCRIPTION
**Pull request by ch3rub1m**

### CODE REVIEW

**Comment by xen0n** [comment]
Change itself is fine, but `urfave/cli` stopped providing its `v2` branch (which is incompatible change and f**k go modules), breaking build. I'm submitting a fix.

**Comment by xen0n** [comment]
@ch3rub1m Hi, mind rebasing and I'll merge?

**Comment by ch3rub1m** [comment]
> @ch3rub1m Hi, mind rebasing and I'll merge?

done

**Comment by xen0n** [comment]
Patch LGTM, thanks for spotting that typo and fixing!

bors r+

**Pull request merged**
